spring:
  application:
    name: athletix-api

  datasource:
    url: jdbc:postgresql://localhost:5432/carreras_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    filter:
      order: 10

app:
  security:
    jwt:
      secret: 4nh3819hn1v38dj184nd1m49xn19vn492n58bpqwbcs8m2iqwoxm4
      expiration: 86400000  # 24 horas en milisegundos
      refreshExpiration: 604800000  # 7 días en milisegundos


# Logging
logging:
  level:
    root: INFO
    com.grupocaos.products.athletix: debug
    org.springframework.security: off
    org.hibernate.SQL: off
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
